# Generated by Django 4.2.1 on 2023-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
